<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRODUCT STORE_modal-backdrop fade show</name>
   <tag></tag>
   <elementGuidId>2d32ca3f-1e33-45b6-92ae-70482ab4afd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-backdrop.fade.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>424fb3d1-52f1-4786-b803-18602ae9e84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-backdrop fade show</value>
      <webElementGuid>7d94a660-37ce-4bc0-aa56-04d58c090e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal-backdrop fade show&quot;]</value>
      <webElementGuid>9733900b-4e03-4c9f-93ea-42d8b0530a09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[9]</value>
      <webElementGuid>0475275f-f485-4db9-ad6f-13e3cbd98629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
